"""Smoke tests for ReportlabCertificatePdfGenerator."""

from __future__ import annotations

import uuid
from datetime import datetime, timezone

from apps.volunteers.infrastructure.pdf import ReportlabCertificatePdfGenerator


def _now() -> datetime:
    return datetime.now(timezone.utc)


class TestReportlabCertificatePdfGenerator:
    """Smoke tests verifying the adapter produces valid PDF bytes."""

    def _make_sut(self) -> ReportlabCertificatePdfGenerator:
        return ReportlabCertificatePdfGenerator()

    def test_returns_bytes(self) -> None:
        """Output is a non-empty bytes object."""
        sut = self._make_sut()
        result = sut.generate(
            certificate_id=uuid.uuid4(),
            volunteer_name="Jane Doe",
            event_name="Tech Fest",
            role_name="Stage Manager",
            hours_worked=4.5,
            rating=5,
            issued_at=_now(),
            verify_url="https://sansaar.com/verify/cert/abc",
        )
        assert isinstance(result, bytes)
        assert len(result) > 0

    def test_output_starts_with_pdf_header(self) -> None:
        """Generated bytes start with the %PDF magic bytes."""
        sut = self._make_sut()
        result = sut.generate(
            certificate_id=uuid.uuid4(),
            volunteer_name="John Smith",
            event_name="Summit",
            role_name="Registration Desk",
            hours_worked=None,
            rating=None,
            issued_at=_now(),
            verify_url="https://sansaar.com/verify/cert/xyz",
        )
        assert result.startswith(b"%PDF")

    def test_generates_without_optional_fields(self) -> None:
        """Works when hours_worked and rating are both None."""
        sut = self._make_sut()
        result = sut.generate(
            certificate_id=uuid.uuid4(),
            volunteer_name="Alice",
            event_name="Gala",
            role_name="Host",
            hours_worked=None,
            rating=None,
            issued_at=_now(),
            verify_url="https://sansaar.com/verify/cert/000",
        )
        assert len(result) > 100
