# Generated by Django 6.0.5 on 2026-05-25 10:34

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("volunteers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VolunteerProfile",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("user_id", models.UUIDField(unique=True)),
                ("average_rating", models.FloatField(blank=True, null=True)),
                ("total_ratings", models.PositiveIntegerField(default=0)),
                ("total_hours", models.FloatField(default=0.0)),
                ("certificate_count", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "volunteers_volunteer_profile",
            },
        ),
        migrations.AddField(
            model_name="volunteerapplication",
            name="feedback",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="volunteerapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                    ("confirmed", "Confirmed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("user_id", models.UUIDField()),
                ("event_id", models.UUIDField()),
                ("pdf_url", models.TextField()),
                ("verify_url", models.TextField()),
                ("issued_at", models.DateTimeField()),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="certificate", to="volunteers.volunteerapplication"
                    ),
                ),
            ],
            options={
                "db_table": "volunteers_certificate",
            },
        ),
        migrations.CreateModel(
            name="VolunteerShift",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("event_id", models.UUIDField()),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("capacity", models.PositiveIntegerField(default=1)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "role",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="shifts", to="volunteers.volunteerrole"),
                ),
            ],
            options={
                "db_table": "volunteers_volunteer_shift",
            },
        ),
    ]
