# Generated by Django 6.0.5 on 2026-05-25 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_add_confirmed_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerapplication',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
