# Generated by Django 6.0.5 on 2026-05-25 03:17

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0003_add_feedback_to_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_id', models.UUIDField(unique=True)),
                ('volunteer_id', models.UUIDField()),
                ('event_id', models.UUIDField()),
                ('org_id', models.UUIDField(blank=True, null=True)),
                ('volunteer_name', models.CharField(max_length=255)),
                ('event_name', models.CharField(max_length=255)),
                ('role_name', models.CharField(max_length=255)),
                ('pdf_url', models.TextField()),
                ('issued_at', models.DateTimeField()),
                ('hours_worked', models.FloatField(blank=True, null=True)),
                ('rating', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': '"volunteers"."certificate"',
            },
        ),
    ]
