# Generated by Django 6.0.5 on 2026-05-17 23:41

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("venues", "0000_create_venues_schema"),
    ]

    operations = [
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("organisation_id", models.UUIDField()),
                ("created_by", models.UUIDField()),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=500)),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("capacity", models.PositiveIntegerField()),
                ("description", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": '"venues"."venue"',
            },
        ),
        migrations.CreateModel(
            name="VenueSpace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("capacity", models.PositiveIntegerField()),
                ("floor", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spaces",
                        to="venues.venue",
                    ),
                ),
            ],
            options={
                "db_table": '"venues"."venue_space"',
            },
        ),
    ]
