# Generated by Django 6.0.5 on 2026-05-30 04:29

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_add_lat_lng_to_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('venue_id', models.UUIDField(db_index=True)),
                ('event_id', models.UUIDField()),
                ('booked_by', models.UUIDField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(default='confirmed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': "venues_venue_booking",
            },
        ),
    ]
