# Generated by Django 6.0.5 on 2026-05-25 03:27

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="communitypost",
            name="reaction_counts",
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name="CommunityPostReaction",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("user_id", models.UUIDField()),
                (
                    "reaction_type",
                    models.CharField(
                        choices=[
                            ("like", "Like"),
                            ("love", "Love"),
                            ("fire", "Fire"),
                            ("laugh", "Laugh"),
                            ("sad", "Sad"),
                            ("angry", "Angry"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="community.communitypost",
                    ),
                ),
            ],
            options={
                "db_table": '"community"."community_post_reaction"',
                "constraints": [models.UniqueConstraint(fields=("post", "user_id"), name="unique_post_reaction_per_user")],
            },
        ),
    ]
