# Generated by Django 6.0.5 on 2026-05-25 03:36

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_add_reaction_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('content', models.TextField()),
                ('is_hidden', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='replies',
                    to='community.postcomment',
                )),
                ('post', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='comments',
                    to='community.communitypost',
                )),
            ],
            options={
                'db_table': '"community"."post_comment"',
            },
        ),
        migrations.CreateModel(
            name='CommentReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('reaction_type', models.CharField(
                    choices=[
                        ('like', 'Like'),
                        ('love', 'Love'),
                        ('fire', 'Fire'),
                        ('laugh', 'Laugh'),
                        ('sad', 'Sad'),
                        ('angry', 'Angry'),
                    ],
                    max_length=10,
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='reactions',
                    to='community.postcomment',
                )),
            ],
            options={
                'db_table': '"community"."comment_reaction"',
                'constraints': [models.UniqueConstraint(fields=('comment', 'user_id'), name='unique_comment_reaction_per_user')],
            },
        ),
    ]
