# Generated by Django 6.0.5 on 2026-05-30 22:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_hashtag_communitypost_author_name_postcomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymember',
            name='avatar_url',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.CreateModel(
            name='ActivityFeed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('user_name', models.CharField(default='', max_length=255)),
                ('user_avatar', models.URLField(blank=True, default='')),
                ('activity_type', models.CharField(max_length=50)),
                ('target_title', models.CharField(default='', max_length=500)),
                ('target_id', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='community.community')),
            ],
            options={
                'db_table': 'community_activity_feed',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventWall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField()),
                ('event_title', models.CharField(max_length=500)),
                ('event_date', models.DateTimeField()),
                ('post_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_walls', to='community.community')),
            ],
            options={
                'db_table': 'community_event_wall',
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('author_id', models.UUIDField()),
                ('author_name', models.CharField(blank=True, default='', max_length=255)),
                ('question', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('total_votes', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='community.community')),
            ],
            options={
                'db_table': 'community_poll',
            },
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('option_index', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='community.poll')),
            ],
            options={
                'db_table': 'community_poll_vote',
                'constraints': [models.UniqueConstraint(fields=('poll', 'user_id'), name='unique_poll_vote')],
            },
        ),
    ]
