# Generated by Django 6.0.5 on 2026-05-22 18:00

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0005_add_org_profile_fields_and_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alloweddomain',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
