# Generated by Django 6.0.5 on 2026-05-29 03:56

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0006_add_org_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='reviewed_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alloweddomain',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
